#!/usr/bin/env node

const shelljs = require('shelljs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const binRoot = path.resolve(root, 'bin')
const fixtureRoot = path.resolve(root, 'test', 'fixtures')
const tmp = shelljs.tempdir()

shelljs
  .cat(path.join(fixtureRoot, 'gigasecond', '2', 'gigasecond.js'))
  .to(path.join(tmp, 'gigasecond.js'))

shelljs.exec(
  `node ${path.join(root, 'dist', 'analyze.js')} gigasecond ${tmp} ${tmp}`
)

const result = JSON.parse(
  shelljs.cat(path.join(tmp, 'analysis.json')).toString()
)

if (result.status !== 'disapprove' || result.comments.length !== 1) {
  console.error('Expected disapprove, with one comment. Actual:', result)
  shelljs.exit(-1)
}

console.log('Tests passed')
shelljs.exit(0)
