#!/usr/bin/env node

import shelljs from 'shelljs'
import { resolve, join } from 'path'

const { tempdir, mkdir, cat, exec, rm, exit } = shelljs

const __dirname = import.meta.dirname

const root = resolve(__dirname, '..')
const binRoot = resolve(root, 'bin')
const fixtureRoot = resolve(root, 'test', 'fixtures')
const tmp = join(tempdir(), 'javascript-analyzer')

mkdir('-p', tmp)

const TESTS = [
  {
    input: {
      fixture: '2',
      slug: 'gigasecond',
      file: 'gigasecond.js',
    },
    expected: {
      comments: 1,
    },
  },
  {
    input: {
      fixture: '36',
      slug: 'resistor-color',
      file: 'resistor-color.js',
    },
    expected: {
      comments: 0,
    },
  },
  {
    input: {
      fixture: '261',
      slug: 'resistor-color-duo',
      file: 'resistor-color-duo.js',
    },
    expected: {
      comments: 1,
    },
  },
  ,
  {
    input: {
      fixture: '408',
      slug: 'two-fer',
      file: 'two-fer.js',
    },
    expected: {
      comments: 1,
    },
  },
]

TESTS.forEach(({ input, expected }) => {
  const out = join(tmp, input.file)

  cat(join(fixtureRoot, input.slug, input.fixture, input.file)).to(out)

  exec(`node ${join(root, 'dist', 'analyze.js')} ${input.slug} ${tmp} ${tmp}`)

  const result = JSON.parse(cat(join(tmp, 'analysis.json')).toString())

  rm(out)
  rm(join(tmp, 'analysis.json'))

  console.log(`Testing ${input.slug} (fixture ${input.fixture})`)

  if (result.comments.length !== expected.comments) {
    console.error(
      `Expected comment count of ${expected.comments}. Actual:`,
      result
    )

    exit(-1)
  }
})

console.log('All e2e tests passed')
exit(0)
