#!/usr/bin/env node

const shelljs = require('shelljs')
const path = require('path')

const binRoot = path.resolve(path.join(__dirname), '..', 'bin')
const fixtureRoot = path.resolve(path.join(__dirname, '..', 'test', 'fixtures'))
const tmp = shelljs.tempdir()

shelljs
  .cat(path.join(fixtureRoot, 'gigasecond', '2', 'gigasecond.js'))
  .to(path.join(tmp, 'gigasecond.js'))

shelljs.exec(`${path.join(binRoot, 'analyze')} gigasecond ${tmp} ${tmp}`)

const result = JSON.parse(
  shelljs.cat(path.join(tmp, 'analysis.json')).toString()
)

if (result.status !== 'disapprove' || result.comments.length !== 1) {
  console.error('Expected disapprove, with one comment. Actual:', result)
  shelljs.exit(-1)
}

shelljs.exit(0)
