# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: javascript-analyzer / main

on:
  push:
    branches: [main]

jobs:
  precheck:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS (16.x)
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Run exercism/javascript-analyzer ci precheck (lint code)
        run: yarn lint

  unit_tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Build the analyzer and run the tests (using Node ${{ matrix.node-version }})
        run: yarn test

      - name: Run end-to-end tests
        run: yarn test:e2e

  smoke_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        with:
          install: true

      - name: Build Docker image and store in cache
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: false
          load: true
          tags: exercism/javascript-analyzer
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
